version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: inversiones_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 200199Ra.
      MYSQL_DATABASE: DB_opt_portafolios
    ports:
      - "3307:3306"
    volumes:
      - ./01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./02_data_load.sql:/docker-entrypoint-initdb.d/02_data_load.sql